language: c
script: make all check
os: ['linux', 'osx']

addons:
  apt:
    packages:
    - libyajl-dev
    - libyaml-dev

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade libyaml; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yajl; fi
